server:
  port: 18080
eureka:
  client:
    register-with-eureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
  application:
    name: system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/changgou_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
